### ISSUE TITLE
Did not reinstall my global modules

### ISSUE THREAD

**Issue by jcrben** [brock/node-reinstall#20]
This script is great, thanks! But there should perhaps be a warning about reinstalling global modules. My global modules were somewhere in /usr/local (maybe /usr/local/lib; I think it came bundled with a node version installed by brew cask) and they didn't get reinstalled. Prior to running this script, my npm had been broken to the point where no npm executable was in the path after running `npm update -g`, and I didn't dig around enough to create a new symlink. I backed them up to a file before running the script so I know what I'm missing.

**Comment by brock** [comment]
Thanks Ben. I'm not sure what options I could offer to resolve your particular use case, since any checks I would perform to find the global modules wouldn't work if they weren't in your PATH.

But I can think of a few ways we could make the installation of the global modules more configurable. Either a confirmation dialog or just another available option. If you have any other thoughts, let me know. Otherwise I'll play around with the idea until I find something that seems to work well.

Thanks for reporting!

**Comment by jcrben** [comment]
In theory maybe you could check [which of the install paths](https://github.com/brock/node-reinstall/blob/master/node-reinstall.sh#L111) has a bunch of global modules and save them? Otherwise you could just put a caveat in the README. I know that npm being so broken that it's not even in the PATH sounds pretty extreme, but people using this script might be in pretty weird situations.

**Comment by brock** [comment]
Here's what I'm thinking about:

Add a new flag `--silent` that would run the script the way it does now, just blasting the directories even if no global modules were found. Otherwise, for new users, the flow would look something like this:

1. Check to see if there are any global modules installed.
2. If no global modules are installed, stop the script and prompt the user before deleting anything, in case they want to try to figure out where the global modules were installed. Continue? Y/n

I don't want existing users to have to go through that prompt every time, but I'm also thinking that most users will have at least one global module installed, so they will never see the prompt. But the `--silent` flag seems to make sense to me from a headless scripting background, where I'd not want to ever have a hung script because of that prompt.

Another idea might be to detect if we're not in an interactive shell and to add the `--silent` flag automatically for those situations.

**Comment by florrain** [comment]
Bump for interest!

```
~ ❯❯❯ node-reinstall 0.12.4                                                                                                                                    ⏎
Completely reinstalling Node, npm.
=> Downloading nvm from git to '/Users/flo/.nvm'
=> Cloning into '/Users/flo/.nvm'...
remote: Counting objects: 3693, done.
remote: Total 3693 (delta 0), reused 0 (delta 0), pack-reused 3693
Receiving objects: 100% (3693/3693), 827.00 KiB | 169.00 KiB/s, done.
Resolving deltas: 100% (2132/2132), done.
Checking connectivity... done.
* (detached from v0.25.1)
  master

=> Source string already in /Users/flo/.bashrc
=> Close and reopen your terminal to start using nvm
######################################################################## 100.0%
Now using node v0.12.4 (npm v2.10.1)
default -> 0.12.4 (-> v0.12.4)
Reinstalling your global npm modules:

npm ERR! addLocal Could not install /Users/flo
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/flo/.nvm/versions/node/v0.12.4/bin/node" "/Users/flo/.nvm/versions/node/v0.12.4/bin/npm" "install" "--global"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code EISDIR
npm ERR! errno -21

npm ERR! EISDIR, read
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/flo/npm-debug.log
node-reinstall is done. 👍
~ ❯❯❯ less /Users/flo/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/Users/flo/.nvm/versions/node/v0.12.4/bin/node',
1 verbose cli   '/Users/flo/.nvm/versions/node/v0.12.4/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose install initial load of /Users/flo/.nvm/versions/node/v0.12.4/lib/package.json
5 verbose readDependencies loading dependencies from /Users/flo/.nvm/versions/node/v0.12.4/lib/package.json
6 silly cache add args [ '.', null ]
7 verbose cache add spec .
8 silly cache add parsed spec { raw: '.',
8 silly cache add   scope: null,
8 silly cache add   name: null,
8 silly cache add   rawSpec: '.',
8 silly cache add   spec: '/Users/flo',
8 silly cache add   type: 'local' }
9 error addLocal Could not install /Users/flo
10 verbose stack Error: EISDIR, read
10 verbose stack     at Error (native)
11 verbose cwd /Users/flo
12 error Darwin 14.3.0
13 error argv "/Users/flo/.nvm/versions/node/v0.12.4/bin/node" "/Users/flo/.nvm/versions/node/v0.12.4/bin/npm" "install" "--global"
14 error node v0.12.4
15 error npm  v2.10.1
16 error code EISDIR
17 error errno -21
18 error EISDIR, read
19 error If you need help, you may report this error at:
19 error     <https://github.com/npm/npm/issues>
20 verbose exit [ -21, true ]
```

**Comment by florrain** [comment]
fyi - I think the reinstall caused some troubles in my config.

```
npm ERR! Attempt to unlock ~/myapp/node_modules/jasmine-expect, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/flo/.npm/_locks/superagent-20b9725d17d0bfba.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/flo/.npm/_locks/superagent-20b9725d17d0bfba.lock failed { [Error: EACCES, open '/Users/flo/.npm/_locks/superagent-20b9725d17d0bfba.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/flo/.npm/_locks/superagent-20b9725d17d0bfba.lock' }
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/flo/.nvm/versions/node/v0.12.4/bin/node" "/Users/flo/.nvm/versions/node/v0.12.4/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1

npm ERR! Attempt to unlock ~/myapp/node_modules/superagent, which hasn't been locked
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     ~/myapp/npm-debug.log
```

Found a post on Stack Overflow that solved it with:
~/myapp ❯❯❯ sudo chown -R $USER ~/.npm                                         ⏎ ✱ ◼
Password:
~/myapp ❯❯❯ sudo chown -R $USER /usr/local/lib/node_modules                      ✱ ◼
chown: /usr/local/lib/node_modules: No such file or directory
~/myapp ❯❯❯ sudo chown -R $USER /usr/local
```

**Comment by brock** [comment]
Thanks for reporting @florrain 
I think I'll proceed with the configuration options for global modules that I outlined above. If you continue to have issues after that update, we'll open a new issue.
