### ISSUE TITLE
Access denied?

### ISSUE THREAD

**Issue by alohavolha** [brock/node-reinstall#35]
I love the idea! Thank you for putting it all together. 
But I tried and it failed. Any idea what i did wrong?
Here is what I put in the terminal: "
-----------------------------------------------------------------------------------------------
Users-MacBook-9:~ User$ cd myWebsite
Users-MacBook-9:myWebsite User$ git clone git@github.com:brock/node-reinstall.git
Cloning into 'node-reinstall'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Users-MacBook-9:myWebsite User$ git clone git@github.com:brock/node-reinstall.git
Cloning into 'node-reinstall'...
cd node-reinstall

Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Users-MacBook-9:myWebsite User$ cd node-reinstall
-bash: cd: node-reinstall: No such file or directory
Users-MacBook-9:myWebsite User$ 
Users-MacBook-9:myWebsite User$ 
"

**Comment by brock** [comment]
@alohavolha 

This happens when you haven't setup "ssh" access for cloning a git repository. 

You will need to delete the directory where you initially cloned the repo and clone it using HTTPS.

I'll update the README, but in the meantime, here is what you'll need to do:

* Remove the directory that you cloned: `rm -rf node-reinstall`
* Re-clone using HTTPS: `git clone https://github.com/brock/node-reinstall.git`
