### ISSUE TITLE
sudo rm -rf $HOME/{local,lib,include,node*,npm,.npm*}

### ISSUE THREAD

**Issue by robinmessage** [brock/node-reinstall#36]
`sudo rm -rf $HOME/{local,lib,include,node*,npm,.npm*}` - this looks like quite a risky line - what if I have other projects installed in a home directory-based local, lib, or include directory?

**Comment by brock** [comment]
It is risky, however it is intended to be thorough covering all the possibly places a typical user might have installed Node. [See more info here](http://stackoverflow.com/a/11178106/2083544) If you have other items in those directories, it would delete them, so you would need to modify the script before running it. If you'd like to add some sort of confirmation dialog prompt, feel free to open a pull request.

**Comment by nootrope** [comment]
FWIW, this bit me in the ass in a moment of desperation where I needed to reinstall but did not read the script beforehand. All the projects I had in ~/local? Gone. My fault for not vetting before running? Yep. Should this have been made explicit out of basic courtesy in the README? Yep.

**Comment by brock** [comment]
Thanks for reporting this @nootrope

To be honest, this is something that has always bothered me. Since the beginning, I've just always let it slide because (as I thought) "What are the odds that someone was using one of these paths for their projects?"

But in the back of my head, I've always thought, "You really don't know what kind of damage this could cause..." For people who are new to Node.js or even new to the command line, this could cause irreparable damage.

I'm just submitted a new version tonight that checks each of the directories for any files and directories that might get deleted. I also updated the README and make it more apparent how much this can actually destroy.

Let me know if you have any feedback. I've tested it a few times, but another set of eyes would be good.

Thanks for reporting this!
